apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ws-kafka-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-ws-kafka-ui
  template:
    metadata:
      labels:
        app: go-ws-kafka-ui
    spec:
      containers:
        - name: go-ws-kafka-ui
          image: adel5210/go-ws-kafka-ui:1.0.2
          ports:
            - containerPort: 3000
          imagePullPolicy: Always